### ISSUE TITLE
After creating new DAOs it takes at least minutes to show up in UI

### ISSUE THREAD

**Issue by RomaSha2010** [near-daos/astro-ui#741] opened 2022-03-07 09:10 UTC
After creating new DAOs it takes at least minutes to show up in UI

**Comment by chluff** [comment] 2022-03-12 18:18
I created a DAO 3 days ago and it still doesn't show up. But I didn't create from the Astro UI so I don't know if it matters here.
[multicall.sputnik-dao.near](https://explorer.near.org/accounts/multicall.sputnik-dao.near)

**Comment by dmytro-almighty** [comment] 2022-04-22 11:14
cant reproduce, sometime it might happens because of the indexer delays - cant be fixed on Astro side

**Closed as completed by dmytro-almighty** 2022-04-22 11:14 UTC
Labels: bug
